mohist:
  check_update: true
  lang: xx_XX
  custom_flags: aaaa bbbb
  check_libraries: true
  disable_mods_blacklist: false
  disable_plugins_blacklist: false
  check_update_auto_download: false
  use_custom_java11: false
  showlogo: true
  optimize_explosions: true
  prevent_from_entering_unloaded_chunks: true
  forge_ignore_optional_mods_version_check: false
  ignore_empty_time: all_worlds
  chunk_unload_delay: 5
  paper_optimization: only_works
  enable_worldedit_fix: true
  networkmanager:
    debug: false
    intercept: []
forge:
  modsblacklist:
    enable: false
    list: aaaa,bbbb
    kickmessage: Use of unauthorized mods
  modswhitelist:
    enable: false
    mods_number: 0
    list: minecraft,forge
    kickmessage: Use of unauthorized mods
  hidejoinmodslist: false
consolecolor:
  info-time: b
  info-level: 2
  info-msg: r
  warn-time: e
  warn-msg: e
  warn-level: e
  trace-level: c
  fatal-time: c
  error-level: c
  error-msg: c
  fatal-msg: c
  error-time: c
  trace-time: c
  fatal-level: c
  trace-msg: c
libraries_black_list: aaaaa;bbbbbb
